version: '3'

services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: redis-server
networks:
  app-network:
    driver: bridge
